### ISSUE TITLE
Release plans for 1.3?

### ISSUE THREAD

**Issue by mf59816** [mpickering/servant-pandoc#2]
Hi there,

we are using servant-pandoc in https://github.com/liqd/thentos, and I think the upgrade to servant-0.4 is still missing on hackage.  Two questions:
1. do you have a release schedule?
2. is there anything I can do to help?

thanks, (-:
matthias

**Comment by mpickering** [comment]
Hopefully tonight or tomorrow.

**Comment by mpickering** [comment]
Everything is ready now but I can't work out why the travis build is failing.

https://travis-ci.org/mpickering/servant-pandoc/jobs/62475798

**Comment by mpickering** [comment]
I need to cleanup `cabal check` I probably won't have time before the weekend.

**Comment by mf59816** [comment]
When i build locally, it works.  My cabal picks semigroupoids-4.3.

semigroupoids-4.3 exports type constructors L, R, but semigroups-4.5 does not:
- http://hackage.haskell.org/package/semigroupoids-4.3/docs/Data-Semigroupoid-Coproduct.html
- http://hackage.haskell.org/package/semigroupoids-4.5/docs/Data-Semigroupoid-Coproduct.html

(Interestingly, if I force semigroupoids to 4.5, profunctors moves from 4.4.1 to 3.3, and still builds.  I wonder why that didn't happen on travis.)

Anyway, I'll try a PR for this.

**Comment by mf59816** [comment]
works!  (-:

see also: https://github.com/ekmett/profunctors/issues/23

where does travis get its unfixed profunctors?  does this have something to do with hackage allowing to change metadata without changing the package version?

**Comment by mf59816** [comment]
I also cleaned up cabal check, hopefully to your taste.  But it's perfectly fine if you release next week.
